### ISSUE TITLE
Odd results on FreeBSD 11.1?

### ISSUE THREAD

**Issue by RussellHaley** [ldrumm/chronos#8]
I was trying to time something in a script when I noticed the elapsed times didn't make any sense. This is what happens when I run chronos 0.2-2 on freebsd 11.1 from the command line (lua53):
```lua
> t1 = c.nanotime()
> t2 = c.nanotime()
> print(t1)
127268.56963116
> print(t2)
127113.82225496
> print (c.nanotime())
127206.15851052
> print (c.nanotime())
127263.04293764
> print (c.nanotime())
127324.6898754
> print (c.nanotime())
127334.15140992
> print (c.nanotime())
127267.8815914
> print (c.nanotime())
127246.07049476
> 
```

Not sure what to make of that?
Thanks, 
Russ

**Comment by ldrumm** [comment]
Hi Russ

Thanks for the report.
On Fri, May 25, 2018 at 09:29:14PM -0700, Russell Haley wrote:
> I was trying to time something in a script when I noticed the elapsed
> times didn't make any sense. This is what happens when I run chronos
> 0.2-2 on freebsd 11.1 from the command line:
> ```lua
> > t1 = c.nanotime()
> > t2 = c.nanotime()
> > print(t1)
> 127268.56963116
> > print(t2)
> 127113.82225496
[...snip]
> Not sure what to make of that?
Me neither. Please can you provide kernel version information, the
compiler and libc version, and a
brief description of the hardware on which you run? I don't run FreeBSD
here, so I'll see if I can reproduce on a VM, and get to a fix.

Also, is your Lua version modified in any way?

**Comment by RussellHaley** [comment]
Hi, sorry for the delay, I got distracted. 
```
Welcome to fish, the friendly interactive shell
russellh@g1 ~> uname -a
FreeBSD g1.highfell.home 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```
FreeBSD is running in a VBox VM on a 3rd Gen i7 laptop. Lua is built from the standard repository in FreeBSD (ports). Built with the standard clang:

```
russellh@g1 ~> cc --version
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin
```

If you're flummoxed I can ask the guys on the FreeBSD-arm mailing list (I'm a regular) because they know the FreeBSD standard clib better than I do.

**Comment by RussellHaley** [comment]
Okay, I read the massive 176 lines in chronos.c and I think I can handle this. I'll have a look.

**Comment by RussellHaley** [comment]
https://forums.freebsd.org/threads/odd-results-from-clock_gettime-with-clock_monotonic.66058/

**Comment by ldrumm** [comment]
On Mon, May 28, 2018 at 10:18:23PM -0700, Russell Haley wrote:
> https://forums.freebsd.org/threads/odd-results-from-clock_gettime-with-clock_monotonic.66058/
Nice one.

Long story short: Bobi B is correct, and I fundamentally misunderstood the
manpage for `clock_getres`; the multiplier bit *is* the bug. I'll post a
patch and push a new version.

Long story:

I loaded up a virtual machine in virtualbox and ran your example. Nothing looked
out of the ordinary so  I modified your example to print all information:

```c
#include <stdio.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>

int main(int argc, char **argv)
{
  struct timespec t_info;
  static struct timespec res_info = {.tv_nsec = 0, .tv_sec = 0};
  static double multiplier;

  clock_getres(CLOCK_MONOTONIC, &res_info);
  multiplier = 1.0  / (1.e9 / res_info.tv_nsec);
  for (int i = 0; i <= 15; i++) {
    if (clock_gettime(CLOCK_MONOTONIC, &t_info) != 0) {
      printf("clock_gettime() failed:%s", strerror(errno));
    }
    printf(
      "%f with secs=%f, nsecs=%f (res.tv_sec=%f, .tv_nsec = %f)\n",
      t_info.tv_sec + (t_info.tv_nsec * multiplier), (double)t_info.tv_sec,
      (double)t_info.tv_nsec, (double)res_info.tv_sec,
      (double)res_info.tv_nsec
    );
    sleep(1);
  }
}
```

Some version information on the hypervisor
------------------------------------------
`uname -a`:
    Linux host 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
`cat /proc/cpuinfo | grep name | uniq`:
    model name      : Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz
`vboxmanage --version`:
    5.2.12_Debianr122571
virtualization interface: Linux KVM

The Guest
---------
`uname -a`:
     FreeBSD  11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64


Output
------
>> 1172.064404 with secs=1172.000000, nsecs=64404472.000000 (res.tv_sec=0.000000, .tv_nsec = 1.000000)
>> 1173.128755 with secs=1173.000000, nsecs=128754667.000000 (res.tv_sec=0.000000, .tv_nsec = 1.000000)
>> 1174.192332 with secs=1174.000000, nsecs=192332349.000000 (res.tv_sec=0.000000, .tv_nsec = 1.000000)
>> 1175.255944 with secs=1175.000000, nsecs=255943929.000000 (res.tv_sec=0.000000, .tv_nsec = 1.000000)
>> 1176.319519 with secs=1176.000000, nsecs=319518888.000000 (res.tv_sec=0.000000, .tv_nsec = 1.000000)
>> 1177.383141 with secs=1177.000000, nsecs=383140904.000000 (res.tv_sec=0.000000, .tv_nsec = 1.000000)

Looks fine.
However, something curious happens when I give the guest more than one of my
host's CPU cores:

    vboxmanage modifyvm freebs --cpus $(( `nproc` / 2 ))

120.785940 with secs=17.000000, nsecs=370664072.000000 (res.tv_sec=0.000000, .tv_nsec = 280.000000)
139.906824 with secs=18.000000, nsecs=435381515.000000 (res.tv_sec=0.000000, .tv_nsec = 280.000000)
157.057056 with secs=19.000000, nsecs=493060913.000000 (res.tv_sec=0.000000, .tv_nsec = 280.000000)
174.857627 with secs=20.000000, nsecs=553062952.000000 (res.tv_sec=0.000000, .tv_nsec = 280.000000)
192.658589 with secs=21.000000, nsecs=613066388.000000 (res.tv_sec=0.000000, .tv_nsec = 280.000000)
211.047391 with secs=22.000000, nsecs=675169253.000000 (res.tv_sec=0.000000, .tv_nsec = 280.000000)
228.801107 with secs=23.000000, nsecs=735003953.000000 (res.tv_sec=0.000000, .tv_nsec = 280.000000)

...badness.

After some more thorough testing and a quick read of glibc and musl I've found
that modern Linux on amd64 seems to invariably give `.tv_nsec = 1`, which is
probably why such an egregious bug didn't cause errors for me before. The
libc's both just wrap a syscall to `SYS_clock_getres` which eventually ends up
here:
	https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/include/linux/hrtimer.h?h=v4.16.12#n299
If `CONFIG_HIGH_RES_TIMERS` is not defined, the value is actually computed from
the fixed frequency of the hardware PLL chip in jiffies.h:

	https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/include/linux/jiffies.h?h=v4.16.12#n62

My guess is that maintaining timer resolution to such a fine degree on
virtualized multicores is extremely difficult.

Thanks again for the report.

**Comment by ldrumm** [comment]
Sorry didn't mean to close without confirmation this is fixed

**Comment by RussellHaley** [comment]
Yay! Works as expected. Thanks for the syscall walk-through. :)

**Comment by RussellHaley** [comment]
Wheee! (thanks again)

russellh@g1 ~/G/l/test> lua53 insert-random-data.lua 40000
Create: 2.1331559879982 
 Insert 2.4188835219975

readonly disabled
Curren count is 40000.0records to the database
russellh@g1 ~/G/l/test> lua53 insert-random-data.lua 400000
Create: 16.808992358998 
 Insert 20.768217098001

readonly disabled
Curren count is 400000.0records to the database
russellh@g1 ~/G/l/test> lua53 insert-random-data.lua 800000
Create: 36.126357022 
 Insert 41.999741786

readonly disabled
Curren count is 800000.0records to the database
russellh@g1 ~/G/l/test> rm -rf random-data
russellh@g1 ~/G/l/test> lua53 insert-random-data.lua 800000
Create: 36.061416114997 
 Insert 43.123912124

readonly disabled
Curren count is 800000.0records to the database
